application: hd-wifi-1034
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /static
  static_dir: static
- url: .*
  script: main.app

builtins:
- remote_api: on

libraries:
- name: jinja2
  version: latest
